# 服务端口号
server:
  port: 8080

# 数据库地址
datasource:
#  url: localhost:3306/blog_test
  url: 42.192.20.234:3306/blog_test

spring:
  datasource: # 数据库配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
#    password: 123456
    password: mESDAnf5cWyGC45a
    hikari:
      maximum-pool-size: 10 # 最大连接池数
      max-lifetime: 1770000

  #redis相关配置
  redis:
    database: 5
      # 配置redis的主机地址，需要修改成自己的
    host: 42.192.20.234
      #    host: 192.168.1.102
    port: 6379
    password: 123456
    timeout: 5000
      #    lettuce:
      #      pool:
      #        # 连接池中的最大空闲连接，默认值也是8。
      #        max-idle: 8
      #        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
      #        max-wait: -1
      #        # 连接池最大连接数（使用负值表示没有限制） 默认 8
      #        max-active: 8
      #        # 连接池中的最小空闲连接，默认值也是0。
      #        min-idle: 0

    jedis:
      pool:
          # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 500
          # 连接池中的最小空闲连接，默认值也是0。
        min-idle: 50
          # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-active: 1000
          # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 2000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#    static-path-pattern: /static/**
#  web:
#    resources:
#      static-locations: classpath:/static/

mybatis:
  # 指定别名设置的包为所有entity
  type-aliases-package: com.duankaijie.demo.entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范
  mapper-locations: # mapper映射文件位置
    - classpath:mapper/*.xml

logging:
  config: logback.xml
  level:
    com.com.duankaijie.demo.Dao: trace

